/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 30.0
      # io_method: "mmap"
      frame_id: "camera"
      pixel_format: "uyvy"  # see usb_cam/supported_formats for list of supported formats
      # av_device_format: "YUV422P"
      image_width: 1920 
      image_height: 1280
      camera_name: "Tier4C1"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
